### PR TITLE
Recovering SQLJ version in Oracle's translator.jar

### PR DESCRIPTION
**Pull request by finxster**
Hi!

Using Oracle's translator.jar, i'm catching a NoSuchMethodException for sqlj.tools.Sqlj#getVersion() method. This is because sqlj.tools.Sqlj#getVersion() is private.

There's a public method to get sqlj's version, i'm calling it if sqlj.tools.Sqlj#getVersion() fails.

Thanks!

### CODE REVIEW

**Comment by finxster** [comment]
Hello David! Will you release a new version of the plugin?

Thanks!

**Comment by davidkarlsen** [comment]
@finxster Can you please give 1.4-SNAPSHOT a spin - I just deployed latest version to sonatype oss repo: https://oss.sonatype.org/#nexus-search;quick~sqlj-maven-plugin - given everything works ok I can roll a vote.

**Comment by finxster** [comment]
@davidkarlsen doesn't work here:

```
[INFO] --- sqlj-maven-plugin:1.4-SNAPSHOT:sqlj (sqlj) @ sqlj-hello-world ---
[WARNING] Error injecting: org.codehaus.mojo.sqlj.SqljMojo
java.lang.TypeNotPresentException: Type org.codehaus.mojo.sqlj.SqljMojo not present
        at org.eclipse.sisu.space.URLClassSpace.loadClass(URLClassSpace.java:115)
        at org.eclipse.sisu.space.NamedClass.load(NamedClass.java:46)
        at org.eclipse.sisu.space.AbstractDeferredClass.get(AbstractDeferredClass.java:48)
        at com.google.inject.internal.ProviderInternalFactory.provision(ProviderInternalFactory.java:86)
        at com.google.inject.internal.InternalFactoryToInitializableAdapter.provision(InternalFactoryToInitializableAdapter.java:55)
        at com.google.inject.internal.ProviderInternalFactory$1.call(ProviderInternalFactory.java:70)
        at com.google.inject.internal.ProvisionListenerStackCallback$Provision.provision(ProvisionListenerStackCallback.java:100)
        at org.eclipse.sisu.plexus.PlexusLifecycleManager.onProvision(PlexusLifecycleManager.java:133)
        at com.google.inject.internal.ProvisionListenerStackCallback$Provision.provision(ProvisionListenerStackCallback.java:109)
        at com.google.inject.internal.ProvisionListenerStackCallback.provision(ProvisionListenerStackCallback.java:55)
        at com.google.inject.internal.ProviderInternalFactory.circularGet(ProviderInternalFactory.java:68)
        at com.google.inject.internal.InternalFactoryToInitializableAdapter.get(InternalFactoryToInitializableAdapter.java:47)
        at com.google.inject.internal.InjectorImpl$2$1.call(InjectorImpl.java:997)
        at com.google.inject.internal.InjectorImpl.callInContext(InjectorImpl.java:1047)
        at com.google.inject.internal.InjectorImpl$2.get(InjectorImpl.java:993)
        at com.google.inject.Scopes$1$1.get(Scopes.java:59)
        at org.eclipse.sisu.inject.LazyBeanEntry.getValue(LazyBeanEntry.java:82)
        at org.eclipse.sisu.plexus.LazyPlexusBean.getValue(LazyPlexusBean.java:51)
        at org.codehaus.plexus.DefaultPlexusContainer.lookup(DefaultPlexusContainer.java:260)
        at org.codehaus.plexus.DefaultPlexusContainer.lookup(DefaultPlexusContainer.java:252)
        at org.apache.maven.plugin.internal.DefaultMavenPluginManager.getConfiguredMojo(DefaultMavenPluginManager.java:459)
        at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:97)
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:208)
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:153)
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:145)
        at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:84)
        at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:59)
        at org.apache.maven.lifecycle.internal.LifecycleStarter.singleThreadedBuild(LifecycleStarter.java:183)
        at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:161)
        at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:317)
        at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:152)
        at org.apache.maven.cli.MavenCli.execute(MavenCli.java:555)
        at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:214)
        at org.apache.maven.cli.MavenCli.main(MavenCli.java:158)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
        at java.lang.reflect.Method.invoke(Method.java:597)
        at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:289)
        at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:229)
        at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:415)
        at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:356)
Caused by: java.lang.UnsupportedClassVersionError: org/codehaus/mojo/sqlj/SqljMojo : Unsupported major.minor version 51.0
        at java.lang.ClassLoader.defineClass1(Native Method)
        at java.lang.ClassLoader.defineClassCond(ClassLoader.java:631)
        at java.lang.ClassLoader.defineClass(ClassLoader.java:615)
        at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:141)
        at java.net.URLClassLoader.defineClass(URLClassLoader.java:283)
        at java.net.URLClassLoader.access$000(URLClassLoader.java:58)
        at java.net.URLClassLoader$1.run(URLClassLoader.java:197)
        at java.security.AccessController.doPrivileged(Native Method)
        at java.net.URLClassLoader.findClass(URLClassLoader.java:190)
        at org.codehaus.plexus.classworlds.realm.ClassRealm.loadClassFromSelf(ClassRealm.java:389)
        at org.codehaus.plexus.classworlds.strategy.SelfFirstStrategy.loadClass(SelfFirstStrategy.java:42)
        at org.codehaus.plexus.classworlds.realm.ClassRealm.unsynchronizedLoadClass(ClassRealm.java:259)
        at org.codehaus.plexus.classworlds.realm.ClassRealm.loadClass(ClassRealm.java:242)
        at org.codehaus.plexus.classworlds.realm.ClassRealm.loadClass(ClassRealm.java:227)
        at org.eclipse.sisu.space.URLClassSpace.loadClass(URLClassSpace.java:107)
        ... 41 more
```

The 1.3 release was built on jdk7, but it seems that this version was built on jdk8.

**Comment by andham** [comment]
@finxster major.minor version 51.0 means it requires Java 7+. What version are you using?

**Comment by davidkarlsen** [comment]
@finxster Ups - my bad - try now - just pushed an update build with java7

**Comment by andham** [comment]
@davidkarlsen How was this even possible as the target is specified in the project (actually the parent)?

**Comment by finxster** [comment]
Hi @andham, I'm using java6.

**Comment by finxster** [comment]
@davidkarlsen no problem :-)

But even with this new version, I've got the same error.

It's a little strange because seems like 1.3 release was built on jdk7, too...

The new error:

```
[WARNING] Error injecting: org.codehaus.mojo.sqlj.SqljMojo
java.lang.TypeNotPresentException: Type org.codehaus.mojo.sqlj.SqljMojo not present
        at org.eclipse.sisu.space.URLClassSpace.loadClass(URLClassSpace.java:115)
        at org.eclipse.sisu.space.NamedClass.load(NamedClass.java:46)
        at org.eclipse.sisu.space.AbstractDeferredClass.get(AbstractDeferredClass.java:48)
        at com.google.inject.internal.ProviderInternalFactory.provision(ProviderInternalFactory.java:86)
        at com.google.inject.internal.InternalFactoryToInitializableAdapter.provision(InternalFactoryToInitializableAdapter.java:55)
        at com.google.inject.internal.ProviderInternalFactory$1.call(ProviderInternalFactory.java:70)
        at com.google.inject.internal.ProvisionListenerStackCallback$Provision.provision(ProvisionListenerStackCallback.java:100)
        at org.eclipse.sisu.plexus.PlexusLifecycleManager.onProvision(PlexusLifecycleManager.java:133)
        at com.google.inject.internal.ProvisionListenerStackCallback$Provision.provision(ProvisionListenerStackCallback.java:109)
        at com.google.inject.internal.ProvisionListenerStackCallback.provision(ProvisionListenerStackCallback.java:55)
        at com.google.inject.internal.ProviderInternalFactory.circularGet(ProviderInternalFactory.java:68)
        at com.google.inject.internal.InternalFactoryToInitializableAdapter.get(InternalFactoryToInitializableAdapter.java:47)
        at com.google.inject.internal.InjectorImpl$2$1.call(InjectorImpl.java:997)
        at com.google.inject.internal.InjectorImpl.callInContext(InjectorImpl.java:1047)
        at com.google.inject.internal.InjectorImpl$2.get(InjectorImpl.java:993)
        at com.google.inject.Scopes$1$1.get(Scopes.java:59)
        at org.eclipse.sisu.inject.LazyBeanEntry.getValue(LazyBeanEntry.java:82)
        at org.eclipse.sisu.plexus.LazyPlexusBean.getValue(LazyPlexusBean.java:51)
        at org.codehaus.plexus.DefaultPlexusContainer.lookup(DefaultPlexusContainer.java:260)
        at org.codehaus.plexus.DefaultPlexusContainer.lookup(DefaultPlexusContainer.java:252)
        at org.apache.maven.plugin.internal.DefaultMavenPluginManager.getConfiguredMojo(DefaultMavenPluginManager.java:459)
        at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:97)
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:208)
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:153)
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:145)
        at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:84)
        at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:59)
        at org.apache.maven.lifecycle.internal.LifecycleStarter.singleThreadedBuild(LifecycleStarter.java:183)
        at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:161)
        at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:317)
        at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:152)
        at org.apache.maven.cli.MavenCli.execute(MavenCli.java:555)
        at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:214)
        at org.apache.maven.cli.MavenCli.main(MavenCli.java:158)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
        at java.lang.reflect.Method.invoke(Method.java:597)
        at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:289)
        at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:229)
        at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:415)
        at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:356)
Caused by: java.lang.UnsupportedClassVersionError: org/codehaus/mojo/sqlj/SqljMojo : Unsupported major.minor version 51.0
        at java.lang.ClassLoader.defineClass1(Native Method)
        at java.lang.ClassLoader.defineClassCond(ClassLoader.java:631)
        at java.lang.ClassLoader.defineClass(ClassLoader.java:615)
        at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:141)
        at java.net.URLClassLoader.defineClass(URLClassLoader.java:283)
        at java.net.URLClassLoader.access$000(URLClassLoader.java:58)
        at java.net.URLClassLoader$1.run(URLClassLoader.java:197)
        at java.security.AccessController.doPrivileged(Native Method)
        at java.net.URLClassLoader.findClass(URLClassLoader.java:190)
        at org.codehaus.plexus.classworlds.realm.ClassRealm.loadClassFromSelf(ClassRealm.java:389)
        at org.codehaus.plexus.classworlds.strategy.SelfFirstStrategy.loadClass(SelfFirstStrategy.java:42)
        at org.codehaus.plexus.classworlds.realm.ClassRealm.unsynchronizedLoadClass(ClassRealm.java:259)
        at org.codehaus.plexus.classworlds.realm.ClassRealm.loadClass(ClassRealm.java:242)
        at org.codehaus.plexus.classworlds.realm.ClassRealm.loadClass(ClassRealm.java:227)
        at org.eclipse.sisu.space.URLClassSpace.loadClass(URLClassSpace.java:107)
        ... 41 more
```

MANIFEST.MF for 1.3 version:

```
Manifest-Version: 1.0
Built-By: anders
Build-Jdk: 1.7.0_25
Created-By: Apache Maven 3.0.5
Archiver-Version: Plexus Archiver
```

MANIFEST.MF for 1.4-SNAPSHOT version:

```
Manifest-Version: 1.0
Built-By: david
Build-Jdk: 1.7.0_80
Created-By: Apache Maven 3.3.3
Archiver-Version: Plexus Archiver
```

**Comment by andham** [comment]
@finxster What JDK is used for building doesn't matter. What matters is the target config for the compiler, which seems to have changed since 1.3 of the plugin. Not sure that was intentional.

**Comment by finxster** [comment]
@andham maybe target in parent was changed? https://github.com/mojohaus/sqlj-maven-plugin/commit/55bbace4553a5b4525f191b49f32a35ace24498a

**Comment by andham** [comment]
@finxster Yes, the upgrade of the parent caused this. However, I'm not sure it was intentional. i.e. Java 7 is required for the code base or not. If you require Java 6 you should supply a pull request which down grades to 1.6 source and target config for maven-compiler-plugin config!

**Comment by finxster** [comment]
@andham oh, ok! I'll send the pull request.

I need the java6 because of the compatibility with SQLJ's jars.

I don't know about IBM's translator.jar, but with Oracle's version, seems like to be incompatible.

**Comment by davidkarlsen** [comment]
Hi - that wasn't intentional on my side - so commited b8e52d1301252ba5e491eac111f4a18a05e6c787 and uploaded new snapshot - are we rolling now? It´s a bit hard to test for me as I have no SQLJ any longer.

**Comment by andham** [comment]
@davidkarlsen Could we hold for a day or so to verify the snapshot? I'll try to do that myself.

**Comment by davidkarlsen** [comment]
@andham @finxster Yes - "are we rolling" as in "does it work now" :) I'm still waiting for feedback (hopefully from both of you) to verify that it actually works before putting out a vote for it.

**Comment by andham** [comment]
I verified ITs on trunk with IBM SQLJ lib and no errors. Unfortunately I see that there are not tests for the latest changes/PRs. :-(
Personally I'd very much like us to enforce IT to go with new feature PRs. It will be impossible to ensure quality if we don't do that.

**Comment by davidkarlsen** [comment]
@finxster Would you care to add an integration test?
However I have a problem actually running the tests as I don't have access to db2 any longer (and thus the sqlj jar). Are there any other mojohaus'ers that do?

**Comment by finxster** [comment]
@davidkarlsen it works with the current snapshot! I'm using current Oracle's SQLJ lib.
I can do the integration test, but i'm not sure how can I do it without the sqlj lib in classpath...

**Comment by davidkarlsen** [comment]
@finxster Run mvn clean install -Prun-its to test it.
If you are missing the file in your local maven repo you'l get an enforcer error telling you the expected groupId/artifactId/version - and can just do a mvn file:install: https://maven.apache.org/guides/mini/guide-3rd-party-jars-local.html

**Comment by finxster** [comment]
@davidkarlsen Ok! Do you think that will be a good idea to test with oracle's translator.jar too? (I found the problem there)

**Comment by finxster** [comment]
@andham Where did you find IBM's lib? I only found here: http://www.ibm.com/developerworks/data/library/techarticle/dm-0412cline/ but I don't know if is the same that you use.

**Comment by andham** [comment]
@finxster My customer has IBM's DB2 JDBC drivers in their Nexus instance so I used v3.69.24 which I believe is part of DB2 10.5 FP6. I think you should be able to download them from here: http://www-01.ibm.com/support/docview.wss?uid=swg21363866
As part of my work for v1.3 of this plugin I investigated (together with a more license knowledgeable person from the Maven team) if it would be possible to have the IBM sqlj lib in the source repo, but we found that now compliant with the license.
It would be very good to verify with the Oracle lib as I haven't done that.

**Comment by finxster** [comment]
@andham the Oracle's SQLJ lib is inside the Database Client instalation... reading the OTN License Agreement (http://www.oracle.com/technetwork/database/enterprise-edition/downloads/index.html), I found: "You may not: (...) make the Programs available in any manner to any third party (other than Contractors acting on Your behalf as set forth in this Agreement);"

So, I think that we can't use Oracle's lib in the rource repo. Can you confirm if my interpretation is correct?!

**Comment by finxster** [comment]
@andham @davidkarlsen I'm having some trouble to build the project. Is there a problem in my configuration?

```
[INFO]   The post-build script did not succeed. assert new File( basedir, 'target/generated-sources/sqlj/org/acme/TestUNICODE.java' ).exists()
       |         |                                                                    |
       |         |                                                                    false
       |         /home/ac-lalves/workspace/maven-plugin-sqlj-origin/target/it/sqlj-multiple-sqljFiles
       /home/ac-lalves/workspace/maven-plugin-sqlj-origin/target/it/sqlj-multiple-sqljFiles/target/generated-sources/sqlj/org/acme/TestUNICODE.java
```

**Comment by andham** [comment]
@finxster Regarding Oracle's license it doesn't seem to allow for us to include it in the source tree.
@finxster Regarding your issue it looks like one of the ITs fails. What are you building with? Is it with Oracle's translator/SQLJ lib?

**Comment by finxster** [comment]
@andham in fact, 4 of 5 tests fail, the same way I've described before.

I didn't do any extra configuration, just ran the tests (my fork and origin), and both have the same errors.

**Comment by andham** [comment]
@finxster I'm asking about Maven version, JDK, platform OS, etc. And what sqlj lib.

**Comment by davidkarlsen** [comment]
@finxster You should also find a build.log or the likes per test to give you some hints on what's failing

**Comment by finxster** [comment]
@andham ops, sorry. 

This is my configuration:

```
~/workspace/maven-plugin-sqlj-origin$ mvn -version
Apache Maven 3.0.5
Maven home: /usr/share/maven
Java version: 1.6.0_45, vendor: Sun Microsystems Inc.
Java home: /usr/lib/jvm/java-6-oracle/jre
Default locale: en_US, platform encoding: UTF-8
OS name: "linux", version: "3.19.0-33-generic", arch: "amd64", family: "unix"
```

Edit: I'm using IBM's lib: `[INFO] Using SQLJ Translator version 'IBM SQLJ 1.0.34`

**Comment by finxster** [comment]
@davidkarlsen the build.log gave me more information: 

```
[Translating 2 files.]
[Reading file TestUNICODE]
/home/ac-lalves/workspace/maven-plugin-sqlj-origin/target/it/sqlj-classpath-1/src/main/resources/TestUNICODE.sqlj: Error: java.lang.ClassCircularityError: test.com.tmme.x01.TestUNICODE has already been defined
/home/ac-lalves/workspace/maven-plugin-sqlj-origin/target/it/sqlj-classpath-1/src/main/resources/TestUNICODE.sqlj:-1: Error: java.lang.ClassCircularityError: test.com.tmme.x01.TestUNICODE has already been defined
/home/ac-lalves/workspace/maven-plugin-sqlj-origin/target/it/sqlj-classpath-1/src/main/resources/TestUNICODE.sqlj:9.2: Error: java.lang.ClassCircularityError: test.com.tmme.x01.TestUNICODEIterator has already been defined
Total 3 errors.
[INFO] Translated 2 SQLJ files.
```

Edit:
The component's build was successful, but there are errors in post-build script:

```
Running post-build script: /home/ac-lalves/workspace/maven-plugin-sqlj-origin/target/it/sqlj-classpath-1/verify.groovy
Assertion failed:

assert new File( basedir, 'target/generated-sources/sqlj/test/com/tmme/x01/TestUNICODE2.java' ).exists()
       |         |                                                                              |
       |         /home/ac-lalves/workspace/maven-plugin-sqlj-origin/target/it/sqlj-classpath-1  false
       /home/ac-lalves/workspace/maven-plugin-sqlj-origin/target/it/sqlj-classpath-1/target/generated-sources/sqlj/test/com/tmme/x01/TestUNICODE2.java

        at org.codehaus.groovy.runtime.InvokerHelper.assertFailed(InvokerHelper.java:399)
        at org.codehaus.groovy.runtime.ScriptBytecodeAdapter.assertFailed(ScriptBytecodeAdapter.java:655)
        at Script1.run(Script1.groovy:3)
```

**Comment by finxster** [comment]
@andham I think that might be the SQLJ's lib version. Can you confirm what's your version, please?

**Comment by andham** [comment]
@finxster The version of the lib should be printed to the log fil in the very beginning of the sqlj mojo excution. Funny enough, it's what this ticket started out about adding support for when using Oracle's lib. :-)

**Comment by finxster** [comment]
@andham hahaha yes! As soon as I figured out, I edited my answer! Well, my version is: `[INFO] Using SQLJ Translator version 'IBM SQLJ 1.0.34`

**Comment by andham** [comment]
@finxster Looks like a very old version. Most likely there are some compatibility issues with the mojo. I used v3.69.24.

**Comment by finxster** [comment]
@andham You was right. That version was too old, and it works with `IBM SQLJ 3.69.24`. Thanks for your help!

I'm doing some tests here, and I'll update the PR when I'm done.

**Comment by finxster** [comment]
@davidkarlsen @andham I've pushed my test. Can you see if it's ok? 

[UPDATE] https://github.com/finxster/sqlj-maven-plugin/commit/ffb0fb5c9550902a0f439733432874b97c76fc74

If it's ok, Can I send a new pull request? Or can I update this one?

Thanks!

**Comment by andham** [comment]
@finxster I added comment in your commit

**Comment by finxster** [comment]
@andham thanks! Just fix it.

**Comment by finxster** [comment]
Hey @andham @davidkarlsen is it possible the release of the version 1.4 of the plugin? Thanks!

**Comment by finxster** [comment]
Hello @andham or @davidkarlsen 

Will you release a new version?!

Thanks.

**Pull request merged**
